### ISSUE TITLE
distributedListener监听出现交替多次执行现象，而非主节点执行

### ISSUE THREAD

**Issue by xue2lang** [yinjihuan/elastic-job-spring-boot-starter#10]
注解@ElasticJobConf，有个属性“distributedListener”，现在继承AbstractDistributeOnceElasticJobListener类，想在所有分片执行前执行某个操作（即重写方法doBeforeJobExecutedAtLastStarted），发现在控制台进行调用，这个方法持交替性的执行多次，而非单个主节点执行（如：第一次执行了，doBeforeJobExecutedAtLastStarted执行一次，第二次执行了，doBeforeJobExecutedAtLastStarted执行两次，之后交替重复执行  。此现象测试来源于10台机器，分20片得到的结果）

不知道这个情况，其它小伙伴们遇到没有？

**Comment by yinjihuan** [comment]
这个监听器我没用过，官方也说过慎用
![image](https://user-images.githubusercontent.com/17271895/43513774-36fa3dce-95b1-11e8-860c-549d992b95be.png)
