### ISSUE TITLE
EnableElasticJob注解功能无效

### ISSUE THREAD

**Issue by JeffreyPan** [yinjihuan/elastic-job-spring-boot-starter#11]
JobParserAutoConfiguration在@EnableElasticJob中@import、META-INF中spring.factories还有JobParserAutoConfiguration中的@Configuration三个地方注入，导入@EnableElasticJob不加还是能正常使用

**Comment by JeffreyPan** [comment]
导致的问题是@EnableElasticJob功能无效，不加该注解@ElasticJob能正常执行

**Comment by yinjihuan** [comment]
目前是这样设计的，可以加也可以不加，只要引入了starter默认就会开启自动配置，如果不需要使用也没必要引入jar,@EnableElasticJob只是留了这么一个注解
