### ISSUE TITLE
JobService的monitorJobRegister加了个小改动

### ISSUE THREAD

**Issue by shizhengchao** [yinjihuan/elastic-job-spring-boot-starter#12]
当把jo类删掉掉，启动找不到job导致启动失败，在case CHILD_ADDED里加了下面的改动:
if (ClassUtils.isPresent(job.getJobClass(), JobService.class.getClassLoader())) {
						addJob(job);
					} else {
						removeJob(job.getJobName());
					}

**Comment by yinjihuan** [comment]
多谢反馈，下次有更新的时候我加上去

**Comment by yinjihuan** [comment]
这个我没测试出来，目前就是2种情况，一种是动态添加任务的时候，指定的jobClass不存在，是会抛异常的，任务不会增加成功，如果是把对应的job类删掉了，启动报错也是正常的，因为你zk中有配置的信息，job类却不存在了，这个肯定是要抛异常的。
