### ISSUE TITLE
1.0.4 maven 下载不下来，仓库配了。

### ISSUE THREAD

**Issue by xgj1988** [yinjihuan/elastic-job-spring-boot-starter#18]
1.0.4 maven 下载不下来，仓库配了。

**Comment by yinjihuan** [comment]
应该是网络问题吧，那你手动下载放到本地仓库吧
https://jitpack.io/com/github/yinjihuan/elastic-job-spring-boot-starter/1.0.4/elastic-job-spring-boot-starter-1.0.4.jar
