### ISSUE TITLE
转发+EnableElasticJob的修改建议

### ISSUE THREAD

**Issue by jackaudrey** [yinjihuan/elastic-job-spring-boot-starter#19]
感谢楼主的代码，拿来用了！！！
看了一下代码，注解@EnableElasticJob，最终通过import引入了JobParserAutoConfiguration，其实在spring.factories中也配置自动装配：
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
com.cxytiandi.elasticjob.autoconfigure.JobParserAutoConfiguration
这样@EnableElasticJob注解的含义就没有体现出来。
个人理解@EnableElasticJob目的是当检测到系统启动类上有EnableElasticJob时，才启动自动转配，所以，可以修改EnableElasticJob和JobParserAutoConfiguration的定义：
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
public @interface EnableElasticJob{}
--------------------------------------------------------------------
@Configuration
@ConditionalOnBean(annotation = EnableElasticJob.class)
public class JobParserAutoConfiguration {}

**Comment by jackaudrey** [comment]
看了一下代码，注解@EnableElasticJob，最终通过import引入了JobParserAutoConfiguration，其实在spring.factories中也配置自动装配：
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
com.cxytiandi.elasticjob.autoconfigure.JobParserAutoConfiguration
这样@EnableElasticJob注解的含义就没有体现出来。
个人理解@EnableElasticJob目的是当检测到系统启动类上有EnableElasticJob时，才启动自动转配，所以，可以修改EnableElasticJob和JobParserAutoConfiguration的定义：
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
public @interface EnableElasticJob{}
--------------------------------------------------------------------
@Configuration
@ConditionalOnBean(annotation = EnableElasticJob.class)
public class JobParserAutoConfiguration {}

感谢楼主的代码，拿来用了！！！

**Comment by jackaudrey** [comment]
> _No description provided._

**Comment by yinjihuan** [comment]
这个是这样的，之前是注解，后面我想着引入了就自动配置吧，所以就加了配置，这个不冲突的
