### ISSUE TITLE
动态添加任务的bug

### ISSUE THREAD

**Issue by jackaudrey** [yinjihuan/elastic-job-spring-boot-starter#20]
类JobController动态添加SCRIPT任务54行if ("ScriptJob".equals(job.getJobType())) {}，应该修改为if ("ScriptJob".equals(job.getJobType())) {}

**Comment by yinjihuan** [comment]
没看懂，有什么区别

**Comment by jackaudrey** [comment]
写错了，调式的是否发现，传递的任务类别是Script了，if ("ScriptJob".equals(job.getJobType())) {}
我这边改成了
if ("SCRIPT".equals(job.getJobType())) {
}
