### ISSUE TITLE
作业类型jobType值不一致

### ISSUE THREAD

**Issue by zhouyi3625** [yinjihuan/elastic-job-spring-boot-starter#24]
JobController.addJob方法中，if ("ScriptJob".equals(job.getJobType())) {} 中的常量"ScriptJob"是不是应该改为“SCRIPT”？

**Comment by idyoudo** [comment]
也碰到同样的问题，自己在代码中修改为SCRIPT就行

**Comment by yinjihuan** [comment]
后面有其他问题到时候一起修复，多谢

**Comment by yinjihuan** [comment]
已修复：1.0.5版本

<dependency>
	    <groupId>com.github.yinjihuan</groupId>
	    <artifactId>elastic-job-spring-boot-starter</artifactId>
	    <version>1.0.5</version>
</dependency>
