### ISSUE TITLE
动态配置job failover不生效

### ISSUE THREAD

**Issue by wanwenxiu** [yinjihuan/elastic-job-spring-boot-starter#25]
动态添加job(配置了failover=true monitorExecution=true),生成的zookeeper节点上没有失效转移的目录，本地单机调试:手动杀死进程后再重启，就没有继续进行该动态job任务了。而内置的MySimpleJob可以继续进行。
下图是我的动态添加参数和zookeeper节点信息，请问是参数配置错了嘛？
![image](https://user-images.githubusercontent.com/12727888/56937827-554a1a00-6b31-11e9-93cf-ffa58d024926.png)
![image](https://user-images.githubusercontent.com/12727888/56937895-b07c0c80-6b31-11e9-8eec-e257150b8ac3.png)

**Comment by yinjihuan** [comment]
目前动态job是这样设计的，因为原生的ESJob没有带这个功能，这个是我自己扩展加上去的。
我对这个动态任务的设想是某些业务逻辑是一样的，但是会在不同的时间点去执行，比如定时发送新闻，也就是说这个动态任务是一次性的，下次启动是不会再次注册的，如果你的任务需要启动页执行的话，那么没必要用动态任务去添加，直接采取配置的方式。

**Comment by wanwenxiu** [comment]
好的,这几天也已经仔细看了代码逻辑明白了设计原理。感谢回复！

**Comment by yinjihuan** [comment]
主要还是看实际场景，如果确切的需要，这个功能也是可以做的，但我觉得如果是固定的任务肯定还是直接配置比较好，因为动态添加的任务也不好管理，毕竟一个任务逻辑被定时成多次执行了

**Comment by wanwenxiu** [comment]
我们的实际场景就是:能让用户直接添加定时任务。暂时我的思路是：添加job时配置到数据库中。程序运行前读取数据库创建job。

**Comment by yinjihuan** [comment]
这样可以的，至少数据入库了，方便管理

**Comment by wanwenxiu** [comment]
感谢！
