### ISSUE TITLE
配置正确，启动一直报zookeeper注册超时

### ISSUE THREAD

**Issue by henryjun0** [yinjihuan/elastic-job-spring-boot-starter#26]
配置都正确，但是一直报zookeeper注册超时，增加重试次数也不行
![image](https://user-images.githubusercontent.com/41284346/57425369-68ee3280-724d-11e9-8bf2-053b652c12a6.png)

**Comment by yinjihuan** [comment]
zk能连上吗

**Comment by henryjun0** [comment]
> zk能连上吗

能连上，我用spring xm配置，配置一样，可以启动。。。。。不知道为什么

**Comment by henryjun0** [comment]
> zk能连上吗
好了，是我自己的问题，配置文件不知啥时候多加了个等号
