### ISSUE TITLE
ElasticJobConf 注解里只有name属性生效,其余的都是默认值

### ISSUE THREAD

**Issue by 237158596** [yinjihuan/elastic-job-spring-boot-starter#32]
@ElasticJobConf(name = "MySimpleJob",shardingTotalCount=5) 
在execute 时发现  shardingTotalCount 是default 1   
只有在配置文件赋值才有效

**Comment by yinjihuan** [comment]
你注解中指定了值之后，配置文件中有指定么？因为里面优先用配置文件的，当配置文件中不存在时就会用注解中的值，具体代码在JobConfParser中，你可以调试下看看
