### ISSUE TITLE
提个需求

### ISSUE THREAD

**Issue by xgj1988** [yinjihuan/elastic-job-spring-boot-starter#4]
首先非常感谢你这个项目，，但是我们有这样一个需求，就是 开发环境下面 不想用elasticsearch ，测试环境才用，这个时候自然想到了用profile ，但是这里有个问题就是，只要我pom 引用了你的项目，那么就会自动先去连zookeeper 如果没有启动的话，就报错了。然后springboot就退出。所以是否能支持我在真正操作的时候才去看zookeeper 是否连接上，，或者是我用了 指定的profile才生效。。

**Comment by yinjihuan** [comment]
你这个需求很奇怪呀，那你开发环境下可以把@EnableElasticJob去掉啊

**Comment by xgj1988** [comment]
哥们，开发环境下面如何去掉 enableelasticjob呢？
