### ISSUE TITLE
找不到节点，这个错误怎么解决？？？com.dangdang.ddframe.job.reg.exception.RegExceptionHandler.handleException:48 Elastic job: ignored exception for: KeeperErrorCode = NoNode for /elasticJob/MySimpleJob/sharding

### ISSUE THREAD

**Issue by szhjw** [yinjihuan/elastic-job-spring-boot-starter#5]
找不到节点，这个错误怎么解决？？？com.dangdang.ddframe.job.reg.exception.RegExceptionHandler.handleException:48 Elastic job: ignored exception for: KeeperErrorCode = NoNode for /elasticJob/MySimpleJob/sharding

**Comment by yinjihuan** [comment]
启动时候报的吗

**Comment by szhjw** [comment]
解决了，配置出错了，谢谢
