### ISSUE TITLE
jar怎么还没发布到公网上去啊 

### ISSUE THREAD

**Issue by 15168326318** [yinjihuan/elastic-job-spring-boot-starter#6]

**Comment by yinjihuan** [comment]
目前最新版本1.0.1

第一步添加仓库地址：

<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
</repositories>
第二步添加依赖：

<dependency>
	    <groupId>com.github.yinjihuan</groupId>
	    <artifactId>elastic-job-spring-boot-starter</artifactId>
	    <version>1.0.1</version>
</dependency>

**Comment by yinjihuan** [comment]
发布到公网了

**Comment by ShinEDL** [comment]
请问1.0.2是不是没有发布到公网？

**Comment by yinjihuan** [comment]
都发了，在jitpack仓库中
