### ISSUE TITLE
动态job手动触发时会重复执行的bug

### ISSUE THREAD

**Issue by hao86** [yinjihuan/elastic-job-spring-boot-starter#7]
在测试过程中，出现了定时执行正常，但手动触发执行会执行2次job的情况，经过debug发现JobService中应该是重复执行了springJobScheduler的init方法所致，但不明白为什么定时是不执行2次，解决方法是去掉JobService类中addJob方法中最后的springJobScheduler.init();就正常了，不知道作者遇到过没？

**Comment by yinjihuan** [comment]
手动触发是在哪里触发的，我这边看能不能复现下

**Comment by hao86** [comment]
![image](https://user-images.githubusercontent.com/9655248/42682570-8c353b2a-86bd-11e8-91ff-6872d6f1c4c8.png)
是这个自带的管理页面中有触发操作，如果你这也存在这个bug的话，应该是100%复现

**Comment by yinjihuan** [comment]
问题已经解决了，原因是里面有个动态任务添加监听的功能，导致任务重复注册了，代码已提交，目前用了jitPack管理版本，就先不发布了，后面有更多的修改再一起发布，你使用的时候可以把启动类上的
```
//开启动态任务添加API
@ComponentScan(basePackages = {"com.cxytiandi"})
```
去掉就可以了
