### ISSUE TITLE
为什么添加仓库地址啊。我们只配置自己公司的私有地址就可以了。

### ISSUE THREAD

**Issue by 15168326318** [yinjihuan/elastic-job-spring-boot-starter#8]
第一步添加仓库地址：

<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
</repositories>

**Comment by yinjihuan** [comment]
这个是我传过去的，如果你只想用公司的仓库的话就把源码下载自己编译传到你们的仓库
