### ISSUE TITLE
不支持spring-boot2.0+

### ISSUE THREAD

**Issue by eacoyun** [yinjihuan/elastic-job-spring-boot-starter#9]
2.0以上版本不支持驼峰参数，需要修改为"-"方式

@ConfigurationProperties(prefix = "elasticJob.zk")
public class ZookeeperProperties {}
可以修改为
@ConfigurationProperties(prefix = **"elastic-job.zk"**)

@Component
@Configuration
public class JobConfParser implements ApplicationContextAware {
		private String prefix = "elasticJob.";
}
可以修改为：
@Component
@Configuration
public class JobConfParser implements ApplicationContextAware {
		private String prefix = **"elastic-job.";**
}

**Comment by yinjihuan** [comment]
多谢反馈，@ConfigurationProperties(prefix = "elasticJob.zk")这个确实要改，下面的elastic-job可以不用改啊，我测试只需要改上面一个，现在问题是如果要同时支持2个版本，有什么好的方案吗

**Comment by eacoyun** [comment]
下面的我没试过，不过统一点好些。1.X版本我么有使用过，不过使用elastic.job.xxx.xxx应该也可以支持1.X
